version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointment-sqlserver
    ports:
      - "1533:1433"
    environment:
      SA_PASSWORD: "Senha@123"
      ACCEPT_EULA: "Y"